version: '3.3'

services:
  # PHP-FPM - Service
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker-files/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - 9000:80
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:1.16.1
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8100:80"
    volumes:
      - ./:/var/www/html
      - ./docker-files/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - app-network

  # MySQL - Service
  mysql:
    image: mysql:5.7.24
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: toor
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker-files/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

  client_vuejs:
    build:
      context: .
      dockerfile: ./Dockerfile.node
    container_name: client_vuejs
    volumes:
      - ./:/var/www/html
      - /var/www/html/node_modules
    depends_on:
      - "php"

# Volumes
volumes:
  mysql-data:
    driver: local

# Networks
networks:
  app-network:
    driver: bridge
